=== christopherwoodland/explore-iot-operations/AKS-Edge-main/tools/modules/AksEdgeDeploy/aide-ucschema.json
{
    "$id": "https://microsoft.com/aide-userconfig.schema.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "AKS edge Remote Deployment Configuration",
    "type": "object",
    "properties": {
        "SchemaVersion": {
            "type": "string",
            "default": "1.3",
            "description": "Version of the schema/format of the json"
        },
        "Version": {
            "type": "string",
            "default": "1.0",
            "description": "Version of the json instance"
        },
        "AksEdgeProduct": {
            "enum": [
                "AKS Edge Essentials - K8s",
                "AKS Edge Essentials - K3s"
            ],
            "description": "Product name"
        },
        "AksEdgeProductUrl": {
            "type": "string",
            "description": "Product URL for download"
        },
        "Azure": {
            "type": "object",
            "properties": {
                "ClusterName": {
                    "type": "string",
                    "description": "Cluster name to be used when connecting to Azure Arc-enabled Kubernetes"
                },
                "Location": {
                    "type": "string",
                    "description": "Azure Location for creating the resource group"
                },
                "ResourceGroupName": {
                    "type": "string",
                    "description": "Resource group name to be used for Azure Arc-enabled Server/Kubernetes"
                },
                "SubscriptionId": {
                    "type": "GUID",
                    "description": "SubscriptionId to be used for Azure Arc-enabled Server/Kubernetes"
                },
                "TenantId": {
                    "type": "GUID",
                    "description": "TenantId to be used for Azure Arc-enabled Server/Kubernetes"
                },
                "SubscriptionName": {
                    "type": "string",
                    "description": "Subscription Name to be used for creating serviceprincipal"
                },
                "ServicePrincipalName": {
                    "type": "string",
                    "description": "ServicePrincipalName to be used for creating service principal to onboard Arc-enabled Server/Kubernetes"
                },
                "CustomLocationOID":{
                    "type": "string",
                    "description": "ObjectID for the custom locations resource provider to be used for creating custom locations "
                },
                "Auth": {
                    "type": "object",
                    "propertires": {
                        "ServicePrincipalId": {
                            "type": "string",
                            "description": "ServicePrincipalId for ServicePrincipalName to onboard Arc-enabled Server/Kubernetes"
                        },
                        "Password": {
                            "type": "string",
                            "description": "Password corresponding to ServicePrincipalId to onboard Arc-enabled Server/Kubernetes"
                        }
                    }
                },
                "EnableWorkloadIdentity": {
                    "type": "boolean",
                    "description": "Enables Workload Identity (only for AIO)"
                },
                "EnableKeyManagement": {
                    "type": "boolean",
                    "description": "Enables Key management (key rotation) (only for AIO)"
                },
                "GatewayResourceId": {
                    "type": "string",
                    "description": "Resource Id for the Arc Gateway resource (only for AIO)"
                },
                "ConnectedMachineName":{
                    "type": "string",
                    "description": "Connected Machine name used for Azure Arc enabled Server"
                }
            }
        },
        "InstallOptions": {
            "type": "object",
            "properties": {
                "InstallPath": {
                    "type": "string",
                    "description": "Path to install AksEdge software"
                },
                "VhdxPath": {
                    "type": "string",
                    "description": "Path to create/store AksEdge VM Vhdx files"
                }
            }
        },
        "VSwitch": {
            "type": "object",
            "properties": {
                "Name": {
                    "type": "string",
                    "description": "Name of the External vSwitch"
                },
                "AdapterName": {
                    "type": "string",
                    "description": "Name of the Physical Network Adapter"
                }
            }
        },
        "AksEdgeConfigFile": {
            "type": "string",
            "description": "file path for the AKS Edge Deployment Configuration. If AksEdgeConfig object is defined, it supercedes the specification."
        },
        "AksEdgeConfig": {
            "type": "object",
            "$ref": "file:aksedge-dcschema.json",
            "description": "Embedded AKS Edge Deployment Configuration Object."
        }
    }
}

=== christopherwoodland/explore-iot-operations/AKS-Edge-main/tools/aide-userconfig.json
{
    "SchemaVersion":  "1.3",
    "Version":  "1.0",
    "AksEdgeProduct":  "AKS Edge Essentials - K3s",
    "AksEdgeProductUrl":  "https://download.microsoft.com/download/828d40d9-2ca9-442e-b492-0fbcdbeb7ad6/AksEdge-K3s-1.33.5-1.12.269.0.msi",
    "InstallOptions":  {
                           "InstallPath":  "",
                           "VhdxPath":  ""
                       },
    "VSwitch":  {
                    "Name":  "",
                    "AdapterName":  ""
                },
    "Azure":  {
                  "SubscriptionName":  "",
                  "SubscriptionId":  "6bf68138-6ea4-4272-a3db-78e737e132a6",
                  "TenantId":  "16b3c013-d300-468d-ac64-7eda0820b6d3",
                  "ResourceGroupName":  "iot",
                  "ServicePrincipalName":  "",
                  "Location":  "eastus",
                  "CustomLocationOID":  "af89a3ae-8ffe-4ce7-89fb-a615f4083dc3",
                  "EnableWorkloadIdentity":  true,
                  "GatewayResourceId":  "",
                  "Auth":  {
                               "ServicePrincipalId":  "",
                               "Password":  ""
                           }
              },
    "AksEdgeConfigFile":  "aksedge-config.json"
}

=== christopherwoodland/explore-iot-operations/AKS-Edge-main/tools/aio-aide-userconfig.json
{
  "SchemaVersion": "1.3",
  "Version": "1.0",
  "AksEdgeProduct": "AKS Edge Essentials - K3s",
  "AksEdgeProductUrl": "https://download.microsoft.com/download/828d40d9-2ca9-442e-b492-0fbcdbeb7ad6/AksEdge-K3s-1.33.5-1.12.269.0.msi",
  "InstallOptions": {
    "InstallPath": "",
    "VhdxPath": ""
  },
  "VSwitch": {
    "Name": "",
    "AdapterName": ""
  },
  "Azure": {
    "SubscriptionName": "",
    "SubscriptionId": "<subscription-id>",
    "TenantId": "<tenant-id>",
    "ResourceGroupName": "<resourcegroup-name>",
    "ServicePrincipalName": "",
    "Location": "<location>",
    "CustomLocationOID": "<customlocation-oid>",
    "EnableWorkloadIdentity": true,
    "GatewayResourceId": "",
    "Auth": {
      "ServicePrincipalId": "",
      "Password": ""
    }
  },
  "AksEdgeConfigFile": "aio-aksedge-config.json"
}
